{% set name = "keplergl" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9f9a4baab3f944b41657f16bc19b467f807d9c5156432a6ccb18bcfac6a5959

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - jupyter
    - jupyter-packaging
    - pandas
    - geopandas
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.6.3
    - traittypes >=0.2.1
    - pandas >=1.3.1
    - geopandas >=0.9.0
    - shapely >=1.7.1


test:
  requires:
    - python {{ python_min }}
  imports:
    - keplergl

about:
  home: https://github.com/keplergl/kepler.gl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Kepler.gl for Jupyter
  description: |
    This is a simple jupyter widget for kepler.gl, an advanced geospatial
    visualization tool, to render large-scale interactive maps.
  doc_url: https://docs.kepler.gl/docs/keplergl-jupyter

extra:
  recipe-maintainers:
    - lixun910
    - heshan0131
