{% set name = "keplergl" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6542f4a9e3486804f534ba4f259856942ae738328329092927ac3408fba0035

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - jupyter nbextension install --py --sys-prefix keplergl

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - jupyter
    - pandas
    - geopandas
  run:
    - python >=3.6
    - ipywidgets >=7.6.3
    - traittypes >=0.2.1
    - pandas >=1.3.1
    - geopandas >=0.9.0
    - shapely >=1.7.1


test:
  imports:
    - keplergl

about:
  home: https://github.com/keplergl/kepler.gl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Kepler.gl for Jupyter
  description: |
    This is a simple jupyter widget for kepler.gl, an advanced geospatial
    visualization tool, to render large-scale interactive maps.
  doc_url: https://docs.kepler.gl/docs/keplergl-jupyter

extra:
  recipe-maintainers:
    - lixun910
